### ISSUE TITLE
请求适配nonebot2.0.0-beta2

### ISSUE THREAD

**Issue by TTH23** [cscs181/QQ-GitHub-Bot#11]
![7`F1L57_`OH_IMJK@{WSH`7](https://user-images.githubusercontent.com/78184207/163672323-a21776ba-3368-462a-ae8f-2b12f1dda942.png)
![2G%_AZWM(9 J8~UW22C_{A](https://user-images.githubusercontent.com/78184207/163672329-4d156bb8-5713-4c18-9f85-213a4eec7150.png)

**Comment by yanyongyu** [comment]
插件已适配beta版本，图中报错是你的电脑环境有问题，与插件无关，请参考psutil相关问题。
