### ISSUE TITLE
发送状态报错权限不足

### ISSUE THREAD

**Issue by Kimaru-bili** [cscs181/QQ-GitHub-Bot#13]
出现这种错误 谷歌了好一阵子都没解决
平台：android termux上部署的Ubuntu linux
![PPTR~BWOZ7V RW {2 JV(TK](https://user-images.githubusercontent.com/40233772/174254591-69ac4ee0-e207-45e4-9e77-bbddb91714c9.png)

**Comment by yanyongyu** [comment]
看报错是权限不足，你的用户是否具有权限访问/proc文件夹？可以尝试使用sudo或者root用户

**Comment by Kimaru-bili** [comment]
是root用户

**Comment by Kimaru-bili** [comment]
这个文件夹的权限是777

**Comment by Kimaru-bili** [comment]
但是里边有这个文件
![RQHF6T%DLMTXKBTH9XT9 66](https://user-images.githubusercontent.com/40233772/174257326-43444a21-13df-45b4-abf9-8805b39d7564.png)

**Comment by Kimaru-bili** [comment]
我单独用了python shell试了psutil 是好使的

**Comment by yanyongyu** [comment]
`python -c "import psutil; psutil.diskpartitions()"` 可以正常使用么？你的bot启动方式是？

**Comment by Kimaru-bili** [comment]
我尝试一下 bot启动方式是python bot.py

**Comment by Kimaru-bili** [comment]
![QEJN8)(O( WGC6QY N}9R_B](https://user-images.githubusercontent.com/40233772/174258324-80502d78-7497-4cc9-8d49-9d67954bb4ee.png)

**Comment by yanyongyu** [comment]
我少打个下划线（

**Comment by Kimaru-bili** [comment]
方法是不是错了 应该是psutil.disk_partitions

**Comment by Kimaru-bili** [comment]
![CD~PMMF`B1%KFU%P)K{JKG3](https://user-images.githubusercontent.com/40233772/174258640-75bfee80-7cf9-4a56-9b9b-d2bbf372f81b.png)

**Comment by Kimaru-bili** [comment]
裂开了

**Comment by Kimaru-bili** [comment]
单独找还没这个文件 很怪

**Comment by yanyongyu** [comment]
你可以尝试`ls -al /proc` `cat /proc/filesystems`等命令来确认是否有权限

**Comment by Kimaru-bili** [comment]
没有权限 但是我是root用户啊（why？
![OQ6))UW(4GEDC@NH$2BIX_S](https://user-images.githubusercontent.com/40233772/174259466-91830e75-6d09-4b46-8795-a75a28a853c2.png)

**Comment by yanyongyu** [comment]
有没有可能是因为你这是WSL？

**Comment by Kimaru-bili** [comment]
啊不 我这个是android那个 termux部署的ubuntu
root用户甚至改不了这个文件的权限。。。。
![A65XYT{IEJ(K3Z@HA EPPT](https://user-images.githubusercontent.com/40233772/174260025-01bc0dbe-a32a-4a91-861f-9ecbe55a8589.png)

**Comment by Kimaru-bili** [comment]
约等于无解了是吧（o(╥﹏╥)o）

**Comment by Kimaru-bili** [comment]
那无解了 唉 难受 没服务器电脑又不能长时间开着 只能用手机2333
