### ISSUE TITLE
Bug: qq_group in group_subscirption should not be unique

### ISSUE THREAD

**Issue by felinae98** [cscs181/QQ-GitHub-Bot#26]
https://github.com/cscs181/QQ-GitHub-Bot/blob/4aa7c398d1e4e20ad6f7a52892b62ebd463272a6/src/plugins/github/models/group_subscription.py#L18
这里不应该是 unique 的，如果订阅多个事件一定会出现多个相同的 qq_group，导致第二个及之后的事件订阅失败

**Comment by yanyongyu** [comment]
确实手滑复制过来忘记删了
