### ISSUE TITLE
Security: Please enable Autoescaping for Jinja2

### ISSUE THREAD

**Issue by xiaozhu2007** [cscs181/QQ-GitHub-Bot#68]
Using Jinja2 templates without autoescaping enabled leaves application vulnerable to [XSS attacks](https://owasp.org/www-project-top-ten/2017/A72017-Cross-SiteScripting_(XSS).

[Autoescaping](https://flask.palletsprojects.com/en/1.1.x/templating/#controlling-autoescaping) is the concept of automatically escaping special characters. Special characters for HTML, XML and XHTMl are &, >, <, " as well as '. These characters carry specific meanings so need to be replaced by so called entities if you want to use them for text. Not doing so makes application susceptible to Cross Site Scripting (XSS) attacks.

When configuring the Jinja2 environment, the option to use autoescaping on input can be specified. By default, autoescaping is disabled. When enabled, Jinja2 will filter input strings to escape any HTML content submitted via template variables.

https://github.com/cscs181/QQ-GitHub-Bot/blob/2fcc039482000b080210749de237bdb08e18080a/src/plugins/nonebot_plugin_status/__init__.py#L54-L56

**Comment by yanyongyu** [comment]
纯文本模板渲染与html escape无关，请不要混淆场景
