### ISSUE TITLE
Feature:支持使用 `/detail` 指令显示展开后的内容

### ISSUE THREAD

**Issue by XieXiLin2** [cscs181/QQ-GitHub-Bot#72]
如

<details><summary>Details</summary>
<p>

PPP

<details><summary>Details2</summary>

DDD

</details> 

</p>
</details>

希望显示全部展开后的样子

**Comment by yanyongyu** [comment]
https://github.com/cscs181/QQ-GitHub-Bot/commit/ab998ba727d66a0fc9908a3b1c4dc93ebc553442 已支持自动展开 details，在 3.0.0 版本发布
