### ISSUE TITLE
nonebot_plugin_status can't be used

### ISSUE THREAD

**Issue by Harris-H** [cscs181/QQ-GitHub-Bot#9]
![QQ图片20210910104630](https://user-images.githubusercontent.com/57698783/132791309-7e7dd54a-b3dc-43d9-a6d0-092b21c4fa24.png)

It's no use poking
![image](https://user-images.githubusercontent.com/57698783/132791403-844c5380-df4e-442f-a47d-080507c32e48.png)

Can you solve this problem? please

**Comment by yanyongyu** [comment]
1. 请配置机器人管理员

add this config to nonebot config file

eg. `.env`

```
SUPERUSERS=["your qq id"]
```

2. poking is not supported by `go-cqhttp`

you can double click bot avatar instead.

gocq不支持表情戳一戳

你可以使用双击头像的拍一拍

**Comment by Harris-H** [comment]
Solved, Thank you my friend.
